# Generated by Django 6.0 on 2026-01-08 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('is_recurring', models.BooleanField(default=True, help_text='Is this a subscription product?')),
                ('is_archived', models.BooleanField(default=False, help_text='Archive this product')),
                ('product_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', help_text='Product type', max_length=20)),
                ('polar_id', models.CharField(blank=True, help_text='Polar product ID (populated after sync)', max_length=255, null=True, unique=True)),
                ('sync_status', models.CharField(choices=[('draft', 'Draft - Not synced'), ('synced', 'Synced to Polar'), ('sync_failed', 'Sync Failed'), ('needs_update', 'Needs Update')], default='draft', help_text='Sync status with Polar', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last sync time', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Polar Product',
                'verbose_name_plural': 'Polar Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolarCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polar_customer_id', models.CharField(blank=True, help_text='Polar customer ID', max_length=255, null=True, unique=True)),
                ('external_customer_id', models.CharField(help_text='External customer ID (Django user ID)', max_length=255, unique=True)),
                ('email', models.EmailField(help_text='Customer email', max_length=254)),
                ('name', models.CharField(blank=True, help_text='Customer name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Django user', on_delete=django.db.models.deletion.CASCADE, related_name='polar_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Polar Customer',
                'verbose_name_plural': 'Polar Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_amount', models.IntegerField(help_text='Price in cents (e.g., 1000 = $10.00)', validators=[django.core.validators.MinValueValidator(0)])),
                ('price_currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('type', models.CharField(choices=[('one_time', 'One-time'), ('recurring', 'Recurring')], default='recurring', help_text='Price type', max_length=20)),
                ('recurring_interval', models.CharField(blank=True, choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', help_text='Billing interval for recurring prices', max_length=20, null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Archive this price')),
                ('polar_id', models.CharField(blank=True, help_text='Polar price ID (populated after sync)', max_length=255, null=True, unique=True)),
                ('sync_status', models.CharField(choices=[('draft', 'Draft - Not synced'), ('synced', 'Synced to Polar'), ('sync_failed', 'Sync Failed'), ('needs_update', 'Needs Update')], default='draft', help_text='Sync status with Polar', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last sync time', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product this price belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.polarproduct')),
            ],
            options={
                'verbose_name': 'Polar Price',
                'verbose_name_plural': 'Polar Prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Polar event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Event type (e.g., order.paid)', max_length=100)),
                ('payload', models.JSONField(help_text='Full event payload')),
                ('processed', models.BooleanField(default=False, help_text='Has this event been processed?')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When was it processed?', null=True)),
                ('processing_error', models.TextField(blank=True, help_text='Error during processing')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When webhook was received')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', 'processed'], name='billing_web_event_t_e3f298_idx'), models.Index(fields=['received_at'], name='billing_web_receive_6346c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('revoked', 'Revoked')], default='incomplete', help_text='Subscription status', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Start of current billing period', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of current billing period', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Cancel at end of current period')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When subscription was canceled', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When subscription ended', null=True)),
                ('polar_subscription_id', models.CharField(blank=True, help_text='Polar subscription ID (populated after sync)', max_length=255, null=True, unique=True)),
                ('sync_status', models.CharField(choices=[('draft', 'Draft - Not synced'), ('synced', 'Synced to Polar'), ('sync_failed', 'Sync Failed'), ('needs_update', 'Needs Update')], default='draft', help_text='Sync status with Polar', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last sync time', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Last sync error message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who owns this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='billing.polarcustomer')),
                ('price', models.ForeignKey(help_text='Price plan for this subscription', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.polarprice')),
                ('product', models.ForeignKey(help_text='Product being subscribed to', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.polarproduct')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'current_period_end'], name='billing_sub_status_684a21_idx'), models.Index(fields=['customer', 'status'], name='billing_sub_custome_8375ed_idx')],
            },
        ),
    ]
